import json, re, sys
sys.path.insert(0, "/home/user/loftik-video-bot/unfrozen-history")
from uh import state as S

# Patrick Breen gerçek bir kişi: yüzü HİÇ gösterilmez (POV / eller / arkadan). Diğer gerçek kişiler (Reed, Stark) uzaktan ya da arkadan.
P_HANDS = "the narrator's weathered hands of a 51-year-old Irish farmer in frayed brown wool coat sleeves"
PEG = "Peggy (Irish pioneer mother about 40, strong tired face, dark hair pinned under a faded dark blue bonnet or wool shawl, dark brown wool dress, grey knitted shawl)"
KIDS = "the Breen boys (six pioneer boys of different ages from about 4 to 14, plain homespun shirts, wool trousers, patched coats, wool caps)"
BABY = "baby Isabella (an infant under one year old wrapped in a grey wool blanket)"

def plain(v):
    s = re.sub(r"\.\.\.\s*(?=[a-z])", " ", v)
    s = re.sub(r"\.\.\.\s*(?=['A-Z])", ". ", s).replace("...", ".").replace(" — ", ", ").replace("—", ", ")
    def fix(m):
        w = m.group(0)
        return w if w in ("I", "A") else w.lower()
    s = re.sub(r"\b[A-Z]{2,}\b", fix, s)
    s = re.sub(r"([.!?]\s+)([a-z])", lambda m: m.group(1) + m.group(2).upper(), s)
    s = re.sub(r"\.\s*\.", ".", s)
    return s[0].upper() + s[1:]

CTA = (" If you've stayed with me this far... I think this story stayed with you too. If it did, leave a like, and subscribe. "
       "That's how I know you want more stories like this one, and it helps them reach more people.")

scenes = [
 dict(title="Towser", pov=True, beat="SOĞUK AÇILIŞ (0:00) — günlükten gerçek satır", mood="tense",
  v="February the twenty-third, 1847. Today... I shot our dog, Towser. I wrote it down in my little book, the way I write everything down. Outside, the snow has buried our cabin to the roof. My name is Patrick Breen. Eighty-one of us are trapped in these mountains. And my family, all NINE of us... will walk out alive. This is how.",
  img=f"POV inside a dark snowbound log cabin in February 1847: {P_HANDS} hold a small handmade paper notebook and a pencil on a rough wooden table, a tiny fire in a stone hearth, snow pressing against the small window, an empty dog collar of old leather on the table",
  shots=["the narrator's hand writes slowly in a small worn notebook by firelight",
         "snow is pressed against the tiny frosted window of the cabin",
         "an empty old leather dog collar lies on the rough wooden table"],
  sound="wind over deep snow, a small crackling fire, pencil scratching on paper",
  refs=["cabin_in"],
  must=["the narrator is never seen, only his hands (POV)"], must_not=["a dog's body or blood", "the narrator's face"]),
 dict(title="Ten months earlier", pov=False, mood="intrigue",
  v="Ten months earlier. Spring, 1846. We leave our farm in Iowa with seven children, our wagons and a herd of cattle. Thousands of families are heading west this year, to Oregon and California. I am fifty-one years old, an Irishman who has already crossed one ocean. What is one more continent?",
  img="Spring 1846 on the American prairie: a long line of white canvas-covered wagons pulled by teams of oxen, families walking beside them, cattle herded behind, green grass and wildflowers, wide blue sky",
  shots=["a long line of covered wagons rolls slowly across the green prairie",
         "children walk beside an ox team, a boy cracks a whip",
         "cattle are herded behind the wagons under a wide sky"],
  sound="creaking wagon wheels, oxen lowing, prairie wind, children's voices",
  refs=["wagon"]),
 dict(title="My family", pov=True, mood="warm",
  v="My wife, Peggy. Forty years old, and the strongest person I have ever known. Our boys: John, Edward, Patrick, Simon, James and little Peter. And Isabella, not even a year old, in her mother's arms. Every night on the trail, we pray the rosary together. I did not know yet how much we would need it.",
  img=f"POV at an evening campfire beside a covered wagon on the prairie, summer 1846: {PEG} holding {BABY}, {KIDS} sitting around the fire, a wooden rosary in the narrator's hands in the foreground, sunset sky",
  shots=["Peggy rocks the baby gently by the campfire and smiles",
         "the boys sit around the fire, the youngest leans sleepily on an older brother",
         "the narrator's hands pass the beads of a wooden rosary"],
  sound="campfire crackling, crickets, a quiet murmured prayer",
  refs=["peggy", "boys", "wagon"],
  must=["exactly six boys and one baby", "the narrator is never seen, only his hands"], must_not=["the narrator's face"]),
 dict(title="The shortcut", pov=False, mood="intrigue",
  v="In July, at Fort Bridger, we hear about a new route. A man named Lansford Hastings has written a book about it: a shortcut, he says, that will save hundreds of miles. Our group decides to take it. The old trail hands shake their heads. But the rest of us... we just want to reach California before the snow.",
  img="Fort Bridger trading post in July 1846: a small log stockade in a green valley with mountains behind, covered wagons camped outside, emigrant men in wide-brimmed hats gathered around one man reading from an open book, oxen grazing",
  shots=["emigrant men gather around a man reading from an open book",
         "a bearded old trail hand shakes his head and walks away",
         "covered wagons turn off the main trail onto a faint new track"],
  sound="men talking, oxen grazing, wind in grass",
  refs=["wagon"]),
 dict(title="No road", pov=True, mood="tense",
  v="The shortcut is a lie. In the Wasatch Mountains there is no road at all. For weeks, our men cut one themselves, with axes, through forest and boulders. Some days we move one mile. Then comes the salt desert: eighty miles of white crust, with no water and no grass. Our oxen fall... and do not get up.",
  img="POV in August 1846: emigrant men chopping trees with axes in a steep rocky canyon to clear a path for covered wagons; then a vast blinding white salt flat with exhausted oxen and stranded wagons under a burning sun",
  shots=["men swing axes at trees blocking a steep canyon, wagons waiting behind",
         "covered wagons crawl across a blinding white salt flat",
         "an exhausted ox collapses in its yoke on the salt crust"],
  sound="axes chopping, men shouting, then hot silent wind, a heavy ox breathing",
  refs=["wagon"], must_not=["blood", "dead animals in close-up"]),
 dict(title="Driven out", pov=False, mood="tense",
  v="By October we are a month behind, worn out, and angry. In a quarrel by the Humboldt River, a man named James Reed kills another man, John Snyder. The company drives Reed out, ahead of us, into the wilderness. His wife and four children stay behind with us. Nobody knows yet... that Reed will come back.",
  img="October 1846 by a dry river valley in the Nevada desert: a tense crowd of emigrants beside covered wagons, a bearded man on a horse riding away alone toward distant mountains, seen from behind, a woman with four children watching him go",
  shots=["a tense crowd of emigrants stands silently beside the wagons",
         "a lone rider rides away toward distant mountains, seen from behind",
         "a mother holds her four children close and watches him go"],
  sound="dry wind, a horse's hooves fading, a child crying softly",
  refs=["wagon"], must=["the rider is seen only from behind or far away"], must_not=["weapons being used", "blood", "a fight"]),
 dict(title="The lake", pov=True, beat="⚡ KIRILMA 1: göl ve geçit", mood="intrigue",
  v="On the last day of October, we reach a lake below the pass, the final wall of mountains before California. We can SEE the gap at the top. One more climb, and we are through. That night... it starts to snow.",
  img="POV at dusk on 31 October 1846: a cold mountain lake surrounded by dark pine forest and granite peaks, a high notch in the granite ridge above, covered wagons and oxen camped at the lakeshore, the first snowflakes falling",
  shots=["the narrator looks up at a high gap in the granite ridge above the lake",
         "covered wagons camp at the shore of the cold dark lake",
         "the first snowflakes begin to fall on the canvas of a wagon"],
  sound="cold wind over the lake, oxen, the first soft snowfall",
  refs=["lake", "wagon"]),
 dict(title="Turned back", pov=True, mood="tense",
  v="We try. Men, women, children, oxen, all pushing up toward the pass. The snow is so deep we cannot even find the road. Three miles from the summit, we turn back. Later I write it in my book: 'The snow so deep... we were unable to find the road.'",
  img="POV climbing a steep snowy granite slope toward a mountain pass in early November 1846: emigrants and oxen struggling waist-deep in fresh snow, wagons stuck behind, the pass hidden in grey clouds",
  shots=["emigrants and oxen push up a steep slope through deep snow",
         "a man stops, looks up at the clouded pass, and shakes his head",
         "the line of people turns and walks back down the slope"],
  sound="heavy breathing, oxen bellowing, wind, crunching deep snow",
  refs=["lake"]),
 dict(title="Trapped", pov=False, mood="tense",
  v="Then the real storm comes. For eight days it snows, and snows, and does not stop. The pass is closed. Eighty-one of us are trapped on the wrong side of the mountains. Most of us here at the lake... the Donner families a few miles away, at Alder Creek.",
  img="A heavy blizzard in November 1846 at the mountain lake: snow burying covered wagons up to their canvas tops, oxen standing in deep snow, the granite ridge and pass completely hidden by white storm",
  shots=["snow falls thickly on wagons already buried to their canvas tops",
         "oxen stand motionless in the deep snow",
         "the mountain pass disappears behind a white wall of storm"],
  sound="roaring blizzard wind, muffled snowfall",
  refs=["lake", "wagon"]),
 dict(title="The cabin", pov=True, mood="intrigue",
  v="We are lucky in one thing. By the lake stands an old log cabin, built two years before by other emigrants. We take it. Other families build cabins nearby. Ours has a dirt floor, a stone fireplace, and a roof patched with hides and branches. Nine of us... in one small room.",
  img=f"POV inside a small rough log cabin in November 1846: dirt floor, a stone fireplace with a small fire, a low roof patched with ox hides and pine branches, {PEG} hanging a pot over the fire, {KIDS} sitting on blankets on the floor",
  shots=["the narrator's hands pull a hide over a gap in the low roof",
         "Peggy hangs an iron pot over the small fire",
         "the boys sit close together on blankets on the dirt floor"],
  sound="wind outside, small fire crackling, children whispering",
  refs=["cabin_in", "peggy", "boys"]),
 dict(title="Peggy's rule", pov=False, beat="Hayatta kalma kuralı 1", mood="intrigue",
  v="Peggy makes the first rule. Every piece of meat is counted. Every handful of flour. She hides some away, even from me. 'We eat little, so we can eat long,' she says. In November, other cabins eat well. By January... they have nothing.",
  img=f"Inside the dim log cabin by firelight: {PEG} cutting a very small piece of frozen meat with a knife on a wooden board, carefully wrapping the rest in cloth and hiding it in a wooden box, the children watching hungrily",
  shots=["Peggy cuts a very small slice of frozen meat",
         "she wraps the rest in cloth and hides it in a wooden box",
         "the boys watch her quietly from the shadows"],
  sound="knife on wood, fire crackling, wind",
  refs=["cabin_in", "peggy", "boys"]),
 dict(title="The snow takes the cattle", pov=True, mood="tense",
  v="We kill our oxen and cows and freeze the meat in the snow. The snow is our icebox. But the snow also steals from us. In the storms, some of the cattle wander off and are buried. Under ten feet of white, nobody can find them again.",
  img="POV outside the snowbound cabins in December 1846: emigrant men probing deep snow with long poles, searching for buried cattle, cabins buried to the eaves, grey sky, pine trees heavy with snow",
  shots=["men push long poles deep into the snow, searching",
         "a man shakes his head and pulls his pole out empty",
         "the cabins sit buried to their eaves under a grey sky"],
  sound="wind, poles crunching into snow, men calling to each other",
  refs=["lake"], must_not=["dead animals", "blood"]),
 dict(title="The diary", pov=True, mood="intrigue",
  v="I keep my diary every day. The weather, the wind, who is sick. 'Snow about three feet deep.' Then, 'six feet.' Then, 'eight feet on the level.' And in January: 'must be thirteen feet deep.' We dig steps up from our door just to reach the daylight.",
  img=f"POV of {P_HANDS} writing in a small handmade notebook by firelight; then a view up a steep staircase cut into packed snow leading from a cabin door up to a small square of daylight far above",
  shots=["the narrator's hand writes a line in the small notebook",
         "steps cut in packed snow climb from the cabin door toward daylight",
         "a boy climbs the snow steps toward the light above"],
  sound="pencil scratching, wind far above, snow crunching under small feet",
  refs=["cabin_in"]),
 dict(title="The Forlorn Hope", pov=False, beat="⚡ KIRILMA 2: Forlorn Hope", mood="tense",
  v="In December, seventeen of the strongest decide to cross the mountains on homemade snowshoes, to bring help. They call themselves the Forlorn Hope. They take food for six days. The journey will take them thirty-three. Only seven of them... will reach the valley.",
  img="December 1846: a line of seventeen thin emigrant men and women wrapped in blankets walking away from the buried cabins on crude homemade wooden snowshoes, climbing toward the snowy pass, seen from behind, families watching from the snow",
  shots=["men and women tie crude wooden snowshoes to their boots",
         "a line of people climbs toward the pass, seen from behind",
         "families stand in the snow and watch them grow small"],
  sound="wind, snowshoes crunching, a woman calling a goodbye",
  refs=["lake"]),
 dict(title="Christmas", pov=True, mood="sad",
  v="Christmas Day. I write: 'Began to snow yesterday... snowed all night, and snows yet rapidly. Great difficulty in getting wood.' Peggy has saved a little something for the children. We pray. And outside, the wind screams down off the mountains.",
  img=f"POV inside the dark cabin on Christmas Day 1846: {PEG} giving each of {KIDS} a tiny piece of food from a cloth bundle, a single small candle, snow pressing at the window, everyone wrapped in blankets",
  shots=["Peggy hands each boy a tiny piece of food from a cloth bundle",
         "the youngest boy holds it in both hands and smiles",
         "the family bows heads in prayer by a single small candle"],
  sound="howling wind, quiet prayer, a candle flickering",
  refs=["cabin_in", "peggy", "boys"]),
 dict(title="Hides", pov=False, beat="Hayatta kalma kuralı 2", mood="tense",
  v="By January, the meat is gone. So we eat the hides. Peggy cuts the ox hides into strips, singes off the hair, and boils them for hours, until they turn into a thick, grey glue. It tastes of nothing. I write: 'Hides are the only article we depend on. May God send us help.'",
  img=f"Inside the cabin: {PEG} holding a strip of ox hide over the fire to singe off the hair, then stirring a pot of thick grey boiling glue, steam rising, hungry children watching",
  shots=["Peggy holds a strip of ox hide over the flames to burn off the hair",
         "she stirs a pot of thick grey glue as steam rises",
         "a boy takes a spoonful and grimaces, then eats it anyway"],
  sound="sizzling hair, bubbling pot, fire, wind",
  refs=["cabin_in", "peggy", "boys"]),
 dict(title="Nothing wasted", pov=True, mood="tense",
  v="Then the bones. We boil them again and again, and when they give nothing more, we burn them and eat them like crackers. The children catch mice. We chew bark, and twigs, and the leather of old shoes. Nothing is wasted. Nothing.",
  img="POV in the dim cabin: blackened charred ox bones in the embers of the fire, a boy holding up a small field mouse by its tail with a proud thin face, strips of bark and old leather shoe laces on the table",
  shots=["the narrator's hand pulls a charred bone out of the embers",
         "a thin boy proudly holds up a small mouse by its tail",
         "strips of bark and old leather lie on the table"],
  sound="fire crackling, bone cracking, a child's small laugh",
  refs=["cabin_in", "boys"], must_not=["human bones", "skulls"]),
 dict(title="The dying", pov=False, mood="sad",
  v="Others are not so lucky. In the cabins around us, people begin to die. First the weakest: the old, the babies... and the young men who worked the hardest. The ground is frozen hard as iron, so the dead are laid to rest in the snow.",
  img="Grey winter day at the snowbound cabins: two exhausted emigrant men carrying a long shape wrapped in a blanket out of a buried cabin, a woman in a shawl standing at a doorway cut into the snow with her head bowed, pine trees",
  shots=["two thin men carry a blanket-wrapped shape out of a cabin",
         "a woman in a shawl bows her head at the doorway",
         "snow falls softly on a small mound beside the cabins"],
  sound="wind, slow footsteps in snow, a quiet sob",
  refs=["lake"], must=["the body is fully wrapped in a blanket, nothing visible"],
  must_not=["visible corpse, face or limbs of the dead", "blood", "gore"]),
 dict(title="I count", pov=True, mood="sad",
  v="I will be honest with you. Some nights I lie awake... and I count. How many days of hides. How many children. I write: 'May God relieve us all from this difficulty, if it is His holy will.' Writing it is the only thing that keeps my hands from shaking.",
  img=f"POV at night lying on a blanket in the dark cabin, looking at the sleeping family by the dim glow of the fire: {PEG} asleep holding {BABY}, {KIDS} asleep in a row under blankets, the narrator's hand resting on the small notebook",
  shots=["the narrator looks across the dark room at his sleeping children",
         "Peggy sleeps holding the baby close by the dim fire",
         "the narrator's trembling hand rests on the closed notebook"],
  sound="quiet breathing, dying fire, wind over the snow",
  refs=["cabin_in", "peggy", "boys"]),
 dict(title="Voices in the snow", pov=True, beat="⚡ KIRILMA 3: ilk kurtarma", mood="hopeful",
  v="Then, on the eighteenth of February... voices in the snow. Seven men from California! The Forlorn Hope made it, and help has come. But they carry only what a man can carry on his back. And they can take out only those strong enough to walk.",
  img="POV from the top of the snow steps outside the buried cabin in February 1847: seven rescuers in wool coats and fur caps with heavy packs on their backs walking toward the cabins across deep snow, emigrants climbing out of the snow to meet them, bright cold sunlight",
  shots=["seven men with heavy packs appear over the snow",
         "thin emigrants climb out of the snow holes and stumble toward them",
         "a rescuer hands out small pieces of dried beef"],
  sound="distant shouts, crunching snow, a woman crying with joy",
  refs=["lake"]),
 dict(title="Two of our boys", pov=False, mood="sad",
  v="Twenty-three people leave with them, mostly children and mothers. Two of our boys go too, Edward and Simon. Peggy holds them for a long time. The rest of us stay, and wait for the next rescue. We still have hides. Others have nothing at all.",
  img=f"Bright cold morning at the buried cabins: {PEG} hugging two boys tightly at the start of a line of thin emigrants and rescuers heading toward the pass, the rest of {KIDS} standing beside her",
  shots=["Peggy holds two of her boys tightly",
         "the two boys join a line of people walking toward the pass",
         "Peggy watches them go, the baby in her arms"],
  sound="wind, footsteps in snow, a quiet goodbye",
  refs=["peggy", "boys", "lake"]),
 dict(title="Our dog", pov=True, mood="sad",
  v="Five days later, I do the thing I have been putting off. 'Shot Towser today,' I write, 'and dressed his flesh.' Our dog. The children loved him. That same morning, a neighbour comes to borrow meat. They think I have meat to spare. I know to the contrary.",
  img=f"POV at the cabin door cut in the snow: a thin woman in a shawl standing outside asking for food, the narrator's hand on the door, an old leather dog collar hanging on a nail beside the door",
  shots=["an old leather dog collar hangs on a nail by the door",
         "a thin woman in a shawl stands at the door and asks for meat",
         "the narrator slowly shakes his head"],
  sound="wind, a quiet voice asking, a door creaking",
  refs=["cabin_in"], must_not=["the dog's body", "blood", "meat of an animal being butchered"]),
 dict(title="What I will not say", pov=False, mood="sad",
  v="By now, there is talk in the camp that I will not repeat to you. When the living have nothing left... some of them turn to the dead. In my diary, I write only what I hear. And I pray it never comes to that in our cabin.",
  img="Night at the snowbound cabins: dark log cabins buried in snow, one small window glowing faintly, a lone figure standing in the snow outside looking at another cabin, stars and cold moonlight, eerie silence",
  shots=["moonlight falls on the buried cabins",
         "one small window glows faintly in the dark",
         "a lone figure stands in the snow and turns away"],
  sound="dead silence, faint wind, a distant door closing",
  refs=["lake"], must_not=["bodies", "human remains", "blood", "cooking pots with meat", "anything gory"]),
 dict(title="Reed comes back", pov=True, beat="⚡ KIRILMA 4: Reed geri dönüyor", mood="hopeful",
  v="On the first of March, ten more men arrive. And leading them is James Reed. The man we drove out in October. He crossed the mountains... and now he has come back for his family. I write my last line: 'We are to start in two or three days.'",
  img="POV from the cabin roof level on 1 March 1847: a line of ten rescuers with heavy packs crossing the snow toward the buried cabins, a bearded man in a fur cap at the front seen from a distance, a girl running through the snow toward him",
  shots=["ten rescuers cross the bright snow toward the cabins",
         "a girl runs through the snow toward the man at the front",
         "the narrator's hand writes a final line and closes the notebook"],
  sound="shouts of joy, crunching snow, wind",
  refs=["lake"], must=["the leading man is seen only from a distance or from behind"]),
 dict(title="Starved Camp", pov=False, beat="⚡ KIRILMA 5: Starved Camp", mood="tense",
  v="We leave the lake with Reed's party, seventeen of us. Two days out, a blizzard hits. Reed's men are starving too. They push ahead to bring back food... and leave us behind, my family and a few others, around one fire in the snow. Later, people will call this place Starved Camp.",
  img="A violent blizzard high in the Sierra Nevada in March 1847: a small group of emigrants huddled in blankets around a single fire in a hollow in the deep snow, a few rescuers walking away into the white storm, seen from behind",
  shots=["a small group huddles around one fire in a violent blizzard",
         "a few men walk away into the white storm, seen from behind",
         "a mother pulls a blanket over her children's heads"],
  sound="screaming blizzard wind, a struggling fire",
  refs=["peggy", "boys"]),
 dict(title="Peggy's fire", pov=True, mood="tense",
  v="And here, Peggy saves us all. The heat of our fire melts the snow beneath it, and it sinks deeper and deeper into a pit. She keeps it burning. She feeds it every log we have, holds the baby against her chest, and does not sleep. What else happened at that camp... I leave between me and God.",
  img=f"POV looking down into a deep pit melted in the snow, a small fire burning on logs at the bottom, {PEG} kneeling beside it feeding it a log while holding {BABY} inside her shawl, snow walls around, night blizzard above",
  shots=["the fire burns at the bottom of a deep pit melted in the snow",
         "Peggy leans down and feeds a log into the fire",
         "she pulls the baby closer inside her shawl and keeps watch"],
  sound="wind above, fire hissing on wet wood, a baby whimpering",
  refs=["peggy"], must_not=["bodies", "human remains", "blood"]),
 dict(title="John Stark", pov=False, beat="Kurtuluş", mood="hopeful",
  v="After about a week, men come up through the snow: the third rescue. One of them, a big man named John Stark, refuses to leave anyone behind. He carries the little ones on his back, two at a time, all the way down the mountain.",
  img="Bright clear morning in the snowy Sierra Nevada in March 1847: a big broad-shouldered rescuer in a fur cap and wool coat walking down a snowy mountain slope carrying two small children on his back, seen from behind, other rescuers helping thin adults behind him, pine trees and blue sky",
  shots=["a big man lifts two small children onto his back",
         "he walks down the snowy slope with them, seen from behind",
         "other rescuers help the thin survivors walk behind him"],
  sound="crunching snow, heavy breathing, birds returning",
  refs=["boys"], must=["the big rescuer is seen from behind or far away"]),
 dict(title="How we survived", pov=True, mood="warm",
  v="So how did my family survive, when so many did not? Peggy rationed from the very first day. We stayed together. We ate every hide, every bone. We kept a fire... and a reason to live. And we had luck. A lot of luck. And good men who came back for us.",
  img=f"POV in spring 1847 in a green Sacramento Valley meadow: {PEG} sitting on the grass with {BABY}, all {KIDS} together around her, thin but alive, sunlight, an oak tree",
  shots=["Peggy sits in the green grass with the baby in her lap",
         "the boys sit around her in the sunlight, thin but smiling",
         "the narrator's hand rests on Peggy's shoulder"],
  sound="birdsong, a gentle breeze, children's quiet laughter",
  refs=["peggy", "boys"], must=["exactly six boys and one baby"]),
 dict(title="What came after", pov=False, mood="warm",
  v="Of the eighty-seven people who took that shortcut, thirty-nine died. Forty-eight lived. Ours was one of only two families that came out complete. We settled in San Juan Bautista, in California, and ran an inn for travellers. And our baby, Isabella, lived to be nearly ninety: the very last survivor of us all." + CTA,
  img="Sunny California mission town of San Juan Bautista around 1850: a two-storey adobe building with a wooden balcony used as an inn, the white mission church nearby, a stagecoach and horses in front, travellers arriving, green hills",
  shots=["sunlight on a two-storey adobe inn with a wooden balcony",
         "travellers step down from a stagecoach in front of the inn",
         "the white mission church stands quietly nearby"],
  sound="horses, a stagecoach rolling in, church bell in the distance",
  refs=[]),
 dict(title="What comes next", pov=False, beat="SONRAKİ BÖLÜM", mood="intrigue", own_rules=True,
  v="A hundred and thirty-seven years before us, in France, the coldest winter in five hundred years freezes the rivers, the wine in the barrels... and even the sea along the coast. In a small village, a baker has to keep his family alive. How did he do it? That story is next. And here... the fire is still burning.",
  img="A French village in January 1709 in a deep frost: frozen river with ice, snow on steep slate and thatched roofs, a stone bakery with a warm glowing window and smoke from the oven chimney, frost-covered vineyard on the hillside, dawn light",
  shots=["the frozen river shines in grey dawn light beside the village",
         "frost covers the vines on the hillside",
         "a warm light glows in the window of a small stone bakery"],
  sound="frozen silence, cracking ice, a distant church bell",
  refs=[], must=["France in 1709: early 18th-century village"],
  must_not=["1840s American pioneers, covered wagons", "modern objects"]),
]

SHEET = ("Character reference sheet: on the left a full-body front view standing, "
         "on the right a chest-up portrait of the same person; identical original character in both views, single "
         "character only, no other people, no props except those described. ")
refs = {
 "peggy": {"kind": "character", "prompt": SHEET + "Peggy, Irish-American pioneer mother of 1846 about 40, strong tired face, dark hair pinned up under a faded dark blue cotton bonnet, dark brown wool dress to the ankles, grey knitted wool shawl, worn leather boots"},
 "boys": {"kind": "character", "prompt": "Group reference: six pioneer brothers of 1846 standing in a row from oldest to youngest (about 14, 13, 11, 9, 7 and 4 years old), plain homespun linen shirts, brown wool trousers with suspenders, patched wool coats, wool caps, same family resemblance, freckles, brown hair, full body, plain parchment background"},
 "wagon": {"kind": "location", "prompt": "Reference, an 1846 emigrant covered wagon (prairie schooner): wooden wagon box painted blue, white canvas cover over hoops, large wooden wheels with iron tires, pulled by a team of four oxen in wooden yokes, on a dirt trail"},
 "lake": {"kind": "location", "prompt": "Location reference, wide establishing view of a cold mountain lake in the Sierra Nevada in winter 1846: dark pine forest, granite peaks and a high notch-like pass above, deep snow, three small rough log cabins half-buried in snow near the shore, no people, no modern buildings"},
 "cabin_in": {"kind": "location", "prompt": "Location reference, interior of a small rough log cabin of 1846: dirt floor, walls of unpeeled logs chinked with mud, a stone fireplace, low roof of poles patched with ox hides and pine branches, a rough wooden table and bench, blankets on the floor, one tiny window, no people"},
}
for k, r in refs.items():
    r["n"] = k

ep = {
 "id": "ep004", "version": 1,
 "title": "Trapped in the Snow for 4 Months: The Donner Party",
 "title_alt": "How Did Anyone Survive the Donner Party?",
 "title_c": "The Donner Party Diary: How One Family Got Out Alive",
 "thumbnail": "Bright painterly scene: a snow-buried log cabin with only the roof showing, steps cut into the snow, warm light in a tiny window, blue sky over granite peaks; one big word 'TRAPPED' (A/B: '4 MONTHS', and no text)",
 "hook_description": "In the winter of 1846, eighty-one emigrants were trapped by snow in the Sierra Nevada. Patrick Breen kept a diary through all of it, and his whole family walked out alive. This is their story, told in his words.",
 "character": "Patrick Breen (born 1795), a real Irish-born emigrant and member of the Donner Party; dramatized first-person narration based on his diary. His face is never shown.",
 "setting": "The Donner Party: from Iowa in spring 1846 to the snowbound camp at Truckee (now Donner) Lake, winter 1846–47",
 "style": ("Hand-painted gouache and watercolor storybook illustration, visible brush texture, warm amber firelight against "
           "cold blue winter light, cinematic composition, historically accurate American emigrants of 1846: white canvas "
           "covered wagons with oxen, wool coats, homespun shirts, bonnets and shawls, wide-brimmed felt hats, rough log "
           "cabins, Sierra Nevada granite peaks and pine forest, no modern objects, soft painterly detail, "
           "no text, no letters, no watermark"),
 "ref_style": ("Hand-painted gouache and watercolor storybook character reference sheet, same painterly look as the episode, "
               "even neutral lighting, plain warm parchment background, historically accurate 1846 American pioneer "
               "clothing, original person, no text, no labels, no watermark"),
 "motion_suffix": ("Gentle natural motion, soft cuts between shots, painterly style and characters stay consistent across shots, "
                   "no text; historically accurate 1846–47: covered wagons, oxen, log cabins, wool and homespun clothing, "
                   "no modern objects, no vehicles with engines, no electric lights"),
 "cast": {"Peggy": PEG, "Boys": KIDS, "Isabella": BABY},
 "preview_scenes": [1, 2, 3],
 "gates": {},
 "must": ["historically accurate 1846–47 American emigrant details only",
          "1840s clothing: wool coats, homespun shirts, bonnets, shawls, felt hats; covered wagons with white canvas and oxen",
          "the same faces, hair and clothes as in the reference images for every named character",
          "painterly gouache look in every frame"],
 "must_not": ["any text, letters, numbers, captions, logos or watermark",
              "modern objects: zippers, plastic, nylon jackets, rubber boots, sunglasses, modern rifles, backpacks of modern design, metal snow shovels",
              "cars, trains, engines, electric lights, power lines, paved roads, modern houses",
              "Patrick Breen's face: the narrator appears only as hands in POV",
              "gore, blood, corpses, human remains, bones of humans, anything suggesting cannibalism",
              "cowboy clichés: revolvers in holsters, cowboy boots with spurs, Native American war paint or feathered headdresses",
              "extra fingers, deformed hands, duplicated faces",
              "the same person appearing twice in one frame (clones, twins, duplicated characters)"],
 "sources": [
  "Patrick Breen — Diary of Patrick Breen, One of the Donner Party (Nov 1846–Mar 1847; ed. Frederick J. Teggart, 1910)",
  "Ethan Rarick — Desperate Passage: The Donner Party's Perilous Journey West (Oxford University Press, 2008)",
  "Daniel James Brown — The Indifferent Stars Above (William Morrow, 2009)",
  "George R. Stewart — Ordeal by Hunger (1936)",
  "Charles F. McGlashan — History of the Donner Party (1879)",
  "Virginia Reed — letter to Mary Keyes, 16 May 1847",
  "Kristin Johnson (ed.) — \"Unfortunate Emigrants\": Narratives of the Donner Party (Utah State University Press, 1996)",
  "Donner Memorial State Park, California State Parks",
 ],
 "disclosure": ("Patrick Breen was a real member of the Donner Party. His words here are a dramatized first-person narration "
                "based on his diary and on historical research; lines in quotation marks come from his diary. Other "
                "people are portrayed for illustration only. Illustrations and animation were created with AI tools; "
                "narration uses a synthetic voice."),
 "refs": refs,
 "music": [
  {"from": 1, "track": "Frozen_Star.mp3", "title": "Frozen Star", "mood": "soğuk açılış"},
  {"from": 2, "track": "Lost_Frontier.mp3", "title": "Lost Frontier", "mood": "yola çıkış"},
  {"from": 5, "track": "Dark_Times.mp3", "title": "Dark Times", "mood": "kısayol, çöl"},
  {"from": 7, "track": "Ossuary_6_-_Air.mp3", "title": "Ossuary 6 - Air", "mood": "göl, mahsur"},
  {"from": 11, "track": "Crossing_the_Chasm.mp3", "title": "Crossing the Chasm", "mood": "hayatta kalma kuralları"},
  {"from": 15, "track": "Winter_Reflections.mp3", "title": "Winter Reflections", "mood": "Noel, açlık"},
  {"from": 19, "track": "Eternal_Hope.mp3", "title": "Eternal Hope", "mood": "ilk kurtarma"},
  {"from": 22, "track": "Long_Note_Four.mp3", "title": "Long Note Four", "mood": "Towser, Starved Camp"},
  {"from": 26, "track": "Dreams_Become_Real.mp3", "title": "Dreams Become Real", "mood": "kurtuluş"},
 ],
 "next_episode_tease": "The Great Frost of 1709 in France: a village baker keeps his family alive through the coldest winter in 500 years",
 "voice_engine": None,
 "scenes": [],
}
for i, s in enumerate(scenes, 1):
    sc = {"n": i, "title": s["title"], "pov": s["pov"], "narration": plain(s["v"]), "narration_voiced": s["v"],
          "image_prompt": s["img"], "shots": s["shots"], "sound": s["sound"], "refs": s["refs"], "voice_mood": s["mood"]}
    for k in ("beat", "must", "must_not", "own_rules"):
        if s.get(k):
            sc[k] = s[k]
    ep["scenes"].append(sc)
ep003 = S.load_episode("ep003")
ep["voice_engine"] = ep003["voice_engine"]
ep["max_credits"] = 330
ep["music_credit"] = ("Music by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 4.0 — "
                      + ", ".join(f"\"{m['title']}\"" for m in ep["music"]))
S.save_episode(ep)
w = [len(s["narration"].split()) for s in ep["scenes"]]
print(len(w), "sahne", sum(w), "kelime", min(w), max(w), "≈", round(sum(w)/2.81/1.06/60 + len(w)*0.6/60, 1), "dk")
print(S.estimate(ep))
