import json, re, sys
sys.path.insert(0, "/home/user/loftik-video-bot/unfrozen-history")
from uh import state as S

# Kurgusal karakterler (Étienne ailesi). 1709 Büyük Donu gerçek; köy/aile hayalî, Beauce bölgesinde küçük bir pazar kasabası.
# Yeni kurallar (STRATEGY §14 ve etkileşim notu): sert ilk 15 sn, ~%45'te orta soru (sahne 14), abone vaadi kapanışta.
ET = "Étienne (French village baker about 38, lean, short dark beard, flour on his hands and forearms, brown knitted wool cap, off-white linen shirt with rolled sleeves, brown wool waistcoat, long linen apron, wool breeches, grey stockings, wooden clogs)"
JE = "Jeanne (his wife about 34, warm tired face, brown hair under a white linen coif, grey wool bodice and skirt, faded blue apron, red wool shawl)"
PI = "Pierre (their son, 12, thin, curly brown hair, small brown knitted cap, linen shirt, short apron, wool breeches, wooden clogs)"
MA = "Margot (their daughter, 6, round face, light brown braids under a small white linen cap, little grey wool dress, brown shawl)"

def plain(v):
    s = re.sub(r"\.\.\.\s*(?=[a-z])", " ", v)
    s = re.sub(r"\.\.\.\s*(?=['A-Z])", ". ", s).replace("...", ".").replace(" — ", ", ").replace("—", ", ")
    def fix(m):
        w = m.group(0)
        return w if w in ("I", "A") else w.lower()
    s = re.sub(r"\b[A-Z]{2,}\b", fix, s)
    s = re.sub(r"([.!?]\s+)([a-z])", lambda m: m.group(1) + m.group(2).upper(), s)
    s = re.sub(r"\.\s*\.", ".", s)
    return s[0].upper() + s[1:]

scenes = [
 dict(title="Frozen bread", pov=True, beat="SOĞUK AÇILIŞ (0:00) — ilk 15 sn en çarpıcı an", mood="tense",
  v="January, 1709. The wine is freezing in the barrels. The bread on my shelves is frozen so hard... I have to cut it with an AXE. And outside my bakery, the whole town is waiting. My name is Étienne. I am a baker. And this is how my family survived the coldest winter in five hundred years.",
  img=f"Inside a small French village bakery in January 1709, cold blue morning light: {ET} raises a small hatchet over a round dark loaf frozen solid on a wooden counter, frost on the shelves of round loaves, through the small window a line of townspeople in winter clothes waits in the snow",
  shots=["the baker brings a small hatchet down on a frozen round loaf, splinters of crust fly",
         "frost glitters on rows of round loaves on wooden shelves",
         "through the frosted window, a line of townspeople waits in the snow"],
  sound="hatchet striking frozen bread, cold wind, murmuring crowd outside",
  refs=["etienne", "bakery_in"], must_not=["modern bread shapes like baguettes or sliced bread"]),
 dict(title="Three weeks earlier", pov=False, mood="warm",
  v="Three weeks earlier, everything is normal. I bake in a small market town in the Beauce, the wheat country south-west of Paris. From my door, you can see the spires of Chartres cathedral, far across the fields. Every morning before dawn, the whole town comes to me for bread.",
  img="A small French market town in the Beauce in late December 1708, before the frost: stone houses with steep slate and tile roofs, a village church bell tower, a bakery with smoke rising from its oven chimney at dawn, flat brown wheat fields stretching to the horizon where the two mismatched spires of Chartres cathedral rise far away, pale winter sky",
  shots=["dawn light over flat fields with the twin spires of Chartres cathedral on the horizon",
         "smoke rises from the bakery chimney in the small stone town",
         "townspeople in shawls and knitted caps walk toward the bakery in the early light"],
  sound="a rooster, a distant church bell, footsteps on cobbles",
  refs=["town"], must=["the cathedral is small and far away on the horizon"]),
 dict(title="My family", pov=True, mood="warm",
  v="My wife, Jeanne, runs the shop and counts every coin. Our son Pierre is twelve. He is my apprentice, and he already kneads better than I did at his age. And little Margot, six years old, steals the warm crusts when she thinks nobody is looking.",
  img=f"Warm candlelit interior of the bakery shop before dawn, 1708: {JE} counting copper coins at a wooden counter, {PI} kneading dough in a long wooden trough, {MA} secretly taking a warm crust from a basket of round loaves, flour dust in the warm light",
  shots=["Jeanne counts copper coins into small piles on the counter",
         "Pierre kneads a large lump of dough in a wooden trough",
         "Margot sneaks a warm crust from a basket and grins"],
  sound="coins clinking, dough slapping on wood, a child giggling",
  refs=["jeanne", "pierre", "margot", "bakery_in"], must=["exactly one woman, one boy and one girl"]),
 dict(title="The oven", pov=True, mood="warm",
  v="Everything in my life turns around one thing: the oven. A dome of brick and stone, as old as the house. Once it is hot, it holds the heat for hours. It feeds the town... and in winter, it keeps us warm.",
  img=f"The heart of the bakehouse: a large old domed bread oven of brick and stone built into the wall, its arched mouth glowing orange, {ET} sliding round loaves in with a long wooden peel, bundles of firewood stacked beside it",
  shots=["the baker slides round loaves into the glowing oven with a long wooden peel",
         "orange firelight flickers on the curved brick dome",
         "bundles of sticks are stacked neatly beside the oven"],
  sound="crackling fire in the oven, the wooden peel scraping brick",
  refs=["etienne", "bakery_in"]),
 dict(title="The night it came", pov=True, beat="⚡ KIRILMA 1: don geliyor", mood="tense",
  v="On the eve of the feast of the Kings, the fifth of January, the wind turns. It comes from the east... dry and sharp. By morning, the water in the bucket by our bed is solid ice. Jeanne's breath is white... inside our own house.",
  img=f"Dawn on 6 January 1709 in a small plain bedroom above the bakery: a wooden bucket of water frozen solid beside a simple wooden bed, frost ferns on the small window, {JE} sitting up wrapped in a blanket, her breath visible as white vapour, cold blue light",
  shots=["a wooden bucket of water frozen solid, a ladle stuck in the ice",
         "frost ferns spread across the small window",
         "Jeanne sits up in bed, her breath a white cloud in the cold room"],
  sound="howling east wind, creaking timber, silence of deep cold",
  refs=["jeanne"]),
 dict(title="The whole country freezes", pov=False, mood="tense",
  v="In a few days, the whole country freezes. The river stops. The wells freeze. Birds fall from the sky, frozen in the air. And at night, we hear the oak trees in the forest split open... with a crack like a musket shot.",
  img="The French countryside in mid-January 1709 under a hard frost: a small river frozen solid beside the town, a stone well crusted with ice, a frozen oak forest under a clear icy sky, frost on every branch",
  shots=["the small river beside the town lies frozen and silent",
         "ice hangs from the rope and bucket of a stone well",
         "in the frozen forest, frost glitters on the oak branches"],
  sound="deep silence, a sharp crack of splitting wood echoing through the forest",
  refs=["town"], must_not=["dead birds in close-up"]),
 dict(title="Wine and ink", pov=True, mood="intrigue",
  v="In the cellars, the wine freezes and splits the barrels. The bread freezes on the shelves. Customers come in with axes to break their loaves. Even the ink freezes in Jeanne's pot, so she cannot write down who owes us money.",
  img=f"Inside the cold bakery shop in January 1709: {JE} stands at the wooden counter holding a quill over a frozen inkpot and an open account book, frost on the counter; in the corner a small wooden wine barrel with one split stave, red wine frozen into ice bulging out of the crack",
  shots=["frozen red wine bulges from a cracked wooden barrel in a dark cellar",
         "a customer breaks a frozen loaf with a small axe on the counter",
         "Jeanne taps her quill on a frozen inkpot and sighs"],
  sound="ice creaking, an axe chopping, a quill tapping glass",
  refs=["jeanne", "bakery_in"]),
 dict(title="Rule one: the fire never dies", pov=True, beat="Kural 1", mood="intrigue",
  v="So I make my first rule: the oven never goes out. Not for one night. If it dies, the dough will not rise, the water will not melt... and my family freezes. Pierre and I take turns. Every two hours, one of us gets up and feeds the fire.",
  img=f"Night in the dark bakehouse, January 1709: {PI} in a blanket kneeling in front of the glowing arched mouth of the brick oven, pushing a bundle of sticks inside, sleepy eyes, everything else in deep blue shadow",
  shots=["Pierre, wrapped in a blanket, pushes sticks into the glowing oven",
         "the fire flares up and lights his sleepy face",
         "in the dark corner, the baker sleeps sitting against the warm wall"],
  sound="fire catching, wind outside, a boy yawning",
  refs=["pierre", "etienne", "bakery_in"]),
 dict(title="Fighting the cold", pov=True, mood="intrigue",
  v="Baking in this cold is a fight. Every bucket of water has to be melted over the fire. The dough goes stiff and refuses to rise. So we knead it right beside the oven mouth, and cover it with blankets... like a sleeping child.",
  img=f"POV in the bakehouse: {ET} tucking a wool blanket over a long wooden kneading trough full of dough placed right next to the warm oven, an iron pot of melting ice hanging over the fire",
  shots=["chunks of ice melt in an iron pot over the fire",
         "the baker kneads stiff dough beside the oven mouth",
         "he gently tucks a wool blanket over the dough trough"],
  sound="ice hissing in a pot, dough being kneaded, fire",
  refs=["etienne", "bakery_in"]),
 dict(title="No more wood", pov=False, mood="tense",
  v="But an oven eats wood. And wood is running out. The roads are blocked by snow, and the woodcutters cannot reach the forest. In town, people burn their chairs, their tables, even their bed frames. I pay three times the price for every bundle of sticks.",
  img="A snowy street of the small French town in January 1709: a man breaking a wooden chair to burn, a woman carrying broken table legs, a carter with an almost empty cart of firewood surrounded by people holding out coins",
  shots=["a man breaks up a wooden chair in the snowy street",
         "people crowd around a carter with only a few bundles of sticks",
         "the baker hands over coins for one small bundle"],
  sound="wood cracking, people arguing, a horse snorting",
  refs=["town", "etienne"], must_not=["cars or modern carts with rubber tyres"]),
 dict(title="The warm floor", pov=True, mood="warm",
  v="At night, the neighbours come. An old widow. A family whose house has no fire. A carter with frozen hands. They sleep on the floor of the bakehouse, close to the warm bricks. Jeanne counts them every evening. Some nights, there are fifteen.",
  img=f"Night in the bakehouse in January 1709: villagers of all ages sleeping on straw and blankets on the floor close to the warm brick oven, an old widow in a black shawl, a mother with small children, {JE} standing with a candle counting them",
  shots=["villagers lie on straw close to the warm brick oven",
         "an old widow pulls her black shawl tighter and smiles in her sleep",
         "Jeanne walks between them with a candle, counting quietly"],
  sound="soft breathing, a child coughing, the oven ticking with heat",
  refs=["jeanne", "bakery_in"], must=["each person appears only once"]),
 dict(title="The thaw", pov=False, mood="warm",
  v="At the end of January... a miracle. The thaw. The snow melts. The river runs again. People dance in the street. But my father was a farmer, and he taught me one thing: a winter is not over... until the wheat is safe.",
  img="Late January 1709 in the small French town: melting snow dripping from roofs, the river flowing again with floating ice, townspeople celebrating in the street, a couple dancing, pale sunshine",
  shots=["water drips from melting icicles on a slate roof",
         "the river flows again, carrying broken ice",
         "townspeople dance and laugh in the wet street"],
  sound="dripping water, flowing river, laughter and a fiddle",
  refs=["town"]),
 dict(title="The second frost", pov=True, beat="⚡ KIRILMA 2: buzlanma buğdayı öldürüyor", mood="sad",
  v="And then, in February, the frost comes back, harder than before. The melted snow freezes on the fields like glass. Under it, the young wheat that was sleeping in the ground... dies. All of it. Across the whole of France.",
  img="POV kneeling in a flat Beauce wheat field in February 1709: a thick sheet of clear ice covering the earth like glass, tiny blackened wheat shoots trapped underneath, endless frozen fields under a grey sky",
  shots=["a hand brushes snow from a sheet of clear ice over the field",
         "tiny wheat shoots under the ice are black and dead",
         "the frozen fields stretch empty to the horizon"],
  sound="cold wind across the plain, ice creaking",
  refs=[]),
 dict(title="Hide it or sell it?", pov=True, beat="❓ ORTA SORU (~%45) — izleyiciye doğrudan soru", mood="tense",
  v="That is when I understand what is really coming. Not just cold. Hunger. Next summer, there will be no harvest. Every sack of flour in this town is now worth gold... and everyone knows the baker has flour. So tell me honestly, in the comments: if you were me... would you hide it, or sell it?",
  img=f"Dim storeroom behind the bakery, February 1709: {ET} standing between a few remaining sacks of flour, holding a candle, looking toward the door where shadows of townspeople fall across the floor",
  shots=["candlelight falls on a few remaining sacks of flour",
         "the baker looks toward the door, thinking",
         "shadows of waiting people stretch across the floor"],
  sound="a candle flame, muffled voices outside the door",
  refs=["etienne"]),
 dict(title="Prices", pov=False, mood="tense",
  v="The price of wheat doubles. Then it doubles again. A loaf now costs four times what it did at Christmas. Families who always bought white bread now beg for the darkest, cheapest loaf on my shelf. And some cannot buy even that.",
  img="The bakery counter in March 1709: thin townspeople holding out a few copper coins, a mother with a child pointing at the darkest small loaf on the shelf, almost empty shelves",
  shots=["thin hands hold out a few copper coins over the counter",
         "a mother points at the smallest, darkest loaf",
         "the shelves behind the counter are almost empty"],
  sound="coins on wood, low voices, a child asking for bread",
  refs=["bakery_in"]),
 dict(title="Rule two: no white bread", pov=True, beat="Kural 2", mood="intrigue",
  v="So Jeanne and I make a second rule: no white bread. We mix the wheat with barley, oats, ground beans... even the bran we used to give to the pigs. The bread is heavy and grey. But one sack of flour now feeds three times more people.",
  img=f"POV over a wooden kneading trough: {JE} pouring coarse barley and oat flour and bran into wheat flour, {ET}'s floury hands mixing a heavy grey dough, small sacks of different grains around them",
  shots=["Jeanne pours barley flour and bran into the trough",
         "floury hands mix a heavy grey dough",
         "dark round loaves come out of the oven on a wooden peel"],
  sound="flour pouring, dough being kneaded, oven door scraping",
  refs=["jeanne", "etienne", "bakery_in"]),
 dict(title="Rule three: never close the shutters", pov=True, beat="Kural 3", mood="tense",
  v="In Paris, hungry crowds break into bakeries. In our town, too, angry faces gather at my door. Jeanne is afraid. But I make my third rule: I sell at a fair price, I sell to everyone, and I never close the shutters. A baker who hides his flour... does not survive the spring.",
  img=f"The street in front of the bakery in spring 1709: a tense crowd of hungry townspeople gathered at the open bakery window, {ET} standing in the open doorway handing out dark loaves, {JE} anxious behind him",
  shots=["a crowd of hungry faces presses toward the bakery window",
         "the baker opens the wooden shutters wide",
         "he hands a dark loaf to an old woman at the front"],
  sound="an angry murmuring crowd that slowly quiets",
  refs=["etienne", "jeanne", "town"], must_not=["weapons", "violence", "blood"]),
 dict(title="The King's gold", pov=False, mood="intrigue",
  v="News comes from Versailles. The King is at war, and his treasury is empty. They say Louis the Fourteenth has sent his own gold plates to be melted down into coins. If even the King eats from cheaper plates... then we are all in trouble.",
  img="The small town square in early 1709: a royal courier in a long blue coat and tricorne hat, standing beside his horse, reads a printed news sheet aloud to a small worried crowd of townspeople in shawls and knitted caps, snow on the ground, grey sky",
  shots=["a courier on horseback rides into the snowy town square",
         "he reads a printed news sheet aloud to the crowd",
         "townspeople listen with worried faces"],
  sound="a voice reading aloud, wind, distant clinking of metal",
  refs=["town"], must=["the King himself is not shown"], must_not=["the face of Louis XIV", "collage or split screen"]),
 dict(title="Margot", pov=True, mood="sad",
  v="In March, Margot falls ill. A fever, and a cough that will not stop. Half the children in town are coughing. Jeanne sits beside her all night, next to the warm oven wall. I bake, and bake... and pray between every batch.",
  img=f"Night in the bakehouse in March 1709: {MA} lying pale on a straw mattress close to the warm brick oven wall, covered with blankets, {JE} sitting beside her holding a wet cloth on her forehead, one candle",
  shots=["Margot lies pale under blankets close to the warm oven wall",
         "Jeanne presses a cool cloth to her forehead",
         "the baker pauses at the oven and closes his eyes in prayer"],
  sound="a child's cough, the fire, a whispered prayer",
  refs=["margot", "jeanne", "bakery_in"]),
 dict(title="The fever breaks", pov=True, mood="warm",
  v="On the ninth morning, the fever breaks. Margot opens her eyes... and asks for a warm crust. I give her the best one in the oven. Not every family is so lucky. Our church bell rings for funerals almost every day.",
  img=f"Morning light in the bakehouse: {MA} sitting up in blankets, smiling weakly, holding a warm golden crust in both hands, {ET} kneeling beside her; through the window, the small church bell tower in grey light",
  shots=["Margot opens her eyes and smiles weakly",
         "the baker hands her a warm crust",
         "outside, the church bell tower stands against a grey sky"],
  sound="a soft laugh, then a slow distant church bell",
  refs=["margot", "etienne", "bakery_in"]),
 dict(title="Dead fields", pov=True, mood="sad",
  v="In April, the snow is gone. I walk into the fields with an old farmer named Gilles. Where green wheat should be rising... there is nothing. Only black, dead earth, as far as the eye can see. He kneels down... and cries.",
  img=f"April 1709 in the flat Beauce plain: {ET} standing beside an old farmer with white hair, a wide-brimmed felt hat and a worn brown coat kneeling in a field of bare black earth with no green shoots at all, endless empty fields, pale spring sky",
  shots=["the two men walk along an empty brown field",
         "the old farmer kneels and lets dead earth fall through his fingers",
         "the bare fields stretch empty to the horizon"],
  sound="spring wind across empty fields, a skylark, quiet weeping",
  refs=["etienne"]),
 dict(title="Barley", pov=False, beat="⚡ KIRILMA 3: arpa umudu", mood="hopeful",
  v="But Gilles has an idea. 'Barley,' he says. 'It grows fast. Sown now, it can be cut before autumn.' The farmers who can find seed plough the dead fields again and sow barley. Even the parliament in Paris tells them to do it.",
  img="Spring 1709 in the Beauce: farmers ploughing the dead fields again with a horse-drawn wooden plough, a farmer sowing barley seed by hand from a linen bag across his chest, villagers helping, hopeful morning light",
  shots=["a horse pulls a wooden plough through the dead field",
         "a farmer sows seed by hand from a linen bag",
         "children follow, covering the seed with soil"],
  sound="plough blade in soil, a horse, seeds scattering, birdsong",
  refs=[], must_not=["modern tractors or metal machinery"]),
 dict(title="The hungry months", pov=True, mood="sad",
  v="Spring and early summer are the hardest months. There is almost no old grain left, and the new harvest is not ready. People eat nettles, roots, acorns. Pierre and I bake through the night with whatever flour the farmers bring us. Nothing is wasted.",
  img=f"Night in the bakehouse in early summer 1709: {ET} and {PI} baking small dark loaves by the glowing oven, an almost empty flour sack, a basket of gathered nettles and roots on the table",
  shots=["thin villagers gather nettles at the forest edge",
         "Pierre sweeps the last flour from a sack into a bowl",
         "father and son slide small dark loaves into the oven at night"],
  sound="wind in grass, then the night fire of the oven",
  refs=["etienne", "pierre", "bakery_in"]),
 dict(title="The barley harvest", pov=True, mood="hopeful",
  v="Then, in July, the barley comes in. It is not much. But it is enough. The first barley loaf comes out of my oven, dark and rough... and the whole street lines up for it. I think it is the most beautiful bread I have ever baked.",
  img=f"A warm July evening in 1709 at the bakery door: {ET} lifts a dark round barley loaf out of the oven on a long wooden peel, smiling, a line of townspeople waiting at the open door, golden light, sheaves of barley leaning against the wall outside",
  shots=["farmers cut golden barley with sickles under the summer sun",
         "the baker lifts a dark barley loaf from the oven",
         "a long line of smiling townspeople waits at the bakery door"],
  sound="sickles in barley, summer insects, cheerful voices",
  refs=["etienne", "bakery_in", "town"]),
 dict(title="The cost", pov=False, mood="sad",
  v="Not everyone made it. Across France, the cold, the hunger and the sickness that came after took around six hundred thousand lives. In our little town, we buried old people, children... and too many of our friends.",
  img="A small village churchyard in summer 1709: simple wooden crosses among long grass, a stone church with a bell tower, a few townspeople standing quietly with bowed heads, soft evening light",
  shots=["simple wooden crosses stand in the long grass",
         "townspeople stand quietly with bowed heads",
         "evening light falls on the old stone church"],
  sound="a slow church bell, wind in grass, birdsong",
  refs=["town"], must_not=["bodies, coffins opened, skeletons"]),
 dict(title="How we survived", pov=True, beat="ÖZET: kurallar", mood="warm",
  v="So how did my family survive? We never let the fire die. We stretched every handful of flour. We shared our warmth, and we sold fairly, so the town stood with us instead of against us. And we listened to an old farmer who knew about barley.",
  img=f"Warm evening in the bakehouse, late summer 1709: {ET}, {JE}, {PI} and {MA} sitting together at a wooden table by the glowing oven, sharing a dark round loaf, tired but smiling",
  shots=["the family sits together at the table by the oven",
         "the baker breaks a dark loaf and shares it out",
         "Margot leans her head on her mother's shoulder"],
  sound="soft fire, quiet family talk, a cup set on wood",
  refs=["etienne", "jeanne", "pierre", "margot", "bakery_in"], must=["exactly four people: one man, one woman, one boy, one girl"]),
 dict(title="Every January", pov=True, mood="warm",
  v="The next winter is mild. The bakery is still ours. Pierre will be a master baker one day, and Margot... still steals the warm crusts. And every January, on the night of the Kings, I keep the oven burning all night. Just in case.",
  img=f"A calm snowy January night some years later: the small stone bakery with a warm glowing window and smoke rising from the oven chimney, {ET} silhouetted in the doorway, light snow falling",
  shots=["light snow falls on the quiet town at night",
         "smoke rises from the bakery chimney",
         "the baker stands in the warm doorway and looks up at the snow"],
  sound="soft snowfall, a crackling oven, a distant church bell",
  refs=["town", "etienne"]),
 dict(title="Subscribe", pov=True, beat="CTA + abone vaadi (kanal adı yok)", mood="warm",
  v="If you've stayed with me until the last loaf, thank you. Every week, I bring you one more winter that pushed ordinary people to their limit, told by the people who lived through it. If you want the next one, subscribe. And tell me: what would you have saved first?",
  img=f"Close, warm painterly view of {ET}'s floury hands placing a single round loaf on a wooden table beside a candle, the oven glowing softly in the background",
  shots=["floury hands set a round loaf down beside a candle",
         "the candle flame flickers warmly",
         "the oven glows softly in the background"],
  sound="soft crackling fire",
  refs=["bakery_in"]),
 dict(title="What comes next", pov=False, beat="SONRAKİ BÖLÜM", mood="intrigue", own_rules=True,
  v="Far to the east, on the open steppe of Mongolia, winter falls to fifty degrees below zero. There are no walls, no forests, no cellars. Only felt tents, herds of horses and sheep... and a family that must keep every animal alive until spring. How do they do it? That story is next. And here... the oven is still warm.",
  img="The vast open Mongolian steppe in deep winter: white round felt gers with smoke rising from their roof rings, a herd of shaggy horses and sheep in the snow, low snowy hills, an icy pale blue sky with a low sun",
  shots=["smoke rises from the roof ring of a white felt ger on the snowy steppe",
         "a herd of shaggy horses stands together in the snow",
         "the low sun glitters over an endless white plain"],
  sound="steppe wind, horses snorting, a dog barking far away",
  refs=[], must=["traditional Mongolian felt gers and herds, no modern objects"],
  must_not=["France or French buildings", "cars, motorbikes, solar panels, satellite dishes"]),
]

SHEET = ("Character reference sheet: on the left a full-body front view standing, "
         "on the right a chest-up portrait of the same person; identical original character in both views, single "
         "character only, no other people. ")
refs = {
 "etienne": {"kind": "character", "prompt": SHEET + ET},
 "jeanne": {"kind": "character", "prompt": SHEET + JE},
 "pierre": {"kind": "character", "prompt": SHEET + PI},
 "margot": {"kind": "character", "prompt": SHEET + MA},
 "bakery_in": {"kind": "location", "prompt": "Location reference, single image, NO people: interior of a small French village bakery of 1709: a large old domed bread oven of brick and stone built into the back wall with an arched mouth, a long wooden kneading trough, wooden shelves of round loaves, a long wooden peel, bundles of firewood, a heavy wooden counter, small window with wooden shutters, stone floor, beamed ceiling"},
 "town": {"kind": "location", "prompt": "Location reference, single image, NO people: wide view of a small French market town in the Beauce around 1709 in winter: stone houses with steep slate and tile roofs, a stone church with a bell tower, a small stone bakery with an oven chimney, a narrow frozen river with a stone bridge, flat snowy fields around"},
}
for k, r in refs.items():
    r["n"] = k

ep = {
 "id": "ep005", "version": 1,
 "title": "How a French Village Survived the Coldest Winter in 500 Years (1709)",
 "title_alt": "You're a Baker in 1709. Even the Wine Is Freezing.",
 "title_c": "The Great Frost of 1709: How One Baker Kept His Town Alive",
 "thumbnail": "Bright painterly close-up: the baker's face with frost on his eyebrows and beard, holding up a round loaf covered in frost, snowy town and blue sky behind; one big word 'FROZEN' (B: '1709', C: no text)",
 "hook_description": "In January 1709, the coldest winter in five hundred years fell on France. Wine froze in the barrels, rivers stopped, and the wheat died in the ground. Étienne, a village baker, tells how his family and his town survived it.",
 "character": "Étienne, a fictional baker in a small market town in the Beauce region of France, 1709; his wife Jeanne, son Pierre (12) and daughter Margot (6)",
 "setting": "A small market town in the Beauce, south-west of Paris near Chartres, from December 1708 to the summer of 1709 (the Great Frost, 'le Grand Hiver')",
 "style": ("Hand-painted gouache and watercolor storybook illustration, visible brush texture, warm amber oven and candle light "
           "against cold blue winter light, cinematic composition, historically accurate early 18th-century rural France: "
           "linen shirts, wool waistcoats and breeches, wool stockings, wooden clogs, knitted caps and felt hats for men; "
           "white linen coifs, bodices, long wool skirts, aprons and shawls for women; stone houses with slate and tile roofs, "
           "brick domed bread oven, no modern objects, soft painterly detail, no text, no letters, no watermark"),
 "ref_style": ("Hand-painted gouache and watercolor storybook character reference sheet, same painterly look as the episode, "
               "even neutral lighting, plain warm parchment background, historically accurate 1709 French working-class "
               "clothing, original person, no text, no labels, no watermark"),
 "motion_suffix": ("Gentle natural motion, soft cuts between shots, painterly style and characters stay consistent across shots, "
                   "no text; historically accurate France 1709: stone town, brick bread oven, linen and wool clothing, wooden "
                   "clogs, horse-drawn carts, no modern objects, no engines, no electric lights, no glass bottles with labels"),
 "cast": {"Étienne": ET, "Jeanne": JE, "Pierre": PI, "Margot": MA},
 "preview_scenes": [1, 2, 3],
 "gates": {},
 "must": ["historically accurate France in 1709 only",
          "the same faces, hair and clothes as in the reference images for every named character",
          "painterly gouache look in every frame"],
 "must_not": ["any text, letters, numbers, captions, logos or watermark",
              "modern objects: zippers, plastic, electric lights, modern windows, metal machinery, modern bread like baguettes or sliced bread, paper bags",
              "19th or 20th century clothing, top hats, Napoleonic uniforms, berets of modern style",
              "cars, trains, engines, power lines, paved roads, modern houses",
              "gore, blood, corpses, skeletons",
              "extra fingers, deformed hands, duplicated faces",
              "the same person appearing twice in one frame (clones, twins, duplicated characters)",
              "collage, multiple panels, split screen, several pictures in one image: it must be ONE single continuous scene"],
 "sources": [
  "Marcel Lachiver — Les années de misère: la famine au temps du Grand Roi, 1680–1720 (Fayard, 1991)",
  "Emmanuel Le Roy Ladurie — Histoire humaine et comparée du climat, vol. 1: Canicules et glaciers (Fayard, 2004)",
  "Jürg Luterbacher et al. — European Seasonal and Annual Temperature Variability, Trends, and Extremes Since 1500 (Science, 2004)",
  "Louis de Rouvroy, duc de Saint-Simon — Mémoires (on the winter of 1709)",
  "Elisabeth Charlotte, Duchess of Orléans (Liselotte von der Pfalz) — letters, January–February 1709",
 ],
 "disclosure": ("Étienne, Jeanne, Pierre, Margot and Gilles are fictional characters, built from historical accounts of the "
                "Great Frost of 1709 in France. Illustrations and animation were created with AI tools; narration uses a "
                "synthetic voice."),
 "refs": refs,
 "music": [
  {"from": 1, "track": "Frozen_Star.mp3", "title": "Frozen Star", "mood": "soğuk açılış"},
  {"from": 2, "track": "Village_Consort.mp3", "title": "Village Consort", "mood": "kasaba, aile (barok)"},
  {"from": 5, "track": "Ossuary_6_-_Air.mp3", "title": "Ossuary 6 - Air", "mood": "don geliyor"},
  {"from": 8, "track": "Crossing_the_Chasm.mp3", "title": "Crossing the Chasm", "mood": "hayatta kalma kuralları"},
  {"from": 12, "track": "Healing.mp3", "title": "Healing", "mood": "erime"},
  {"from": 13, "track": "Dark_Times.mp3", "title": "Dark Times", "mood": "ikinci don, açlık"},
  {"from": 16, "track": "Winter_Reflections.mp3", "title": "Winter Reflections", "mood": "kurallar 2–3"},
  {"from": 19, "track": "Long_Note_Four.mp3", "title": "Long Note Four", "mood": "Margot, ölü tarlalar"},
  {"from": 22, "track": "Eternal_Hope.mp3", "title": "Eternal Hope", "mood": "arpa"},
  {"from": 26, "track": "Dreams_Become_Real.mp3", "title": "Dreams Become Real", "mood": "kapanış"},
 ],
 "next_episode_tease": "Winter on the Mongolian steppe at −50°C: a herding family keeps its animals alive until spring",
 "voice_engine": None,
 "scenes": [],
}
for s in scenes:
    if "etienne" in s["refs"]: s["pov"] = False  # anlatıcı görünüyorsa POV ifadesi çelişir
for i, s in enumerate(scenes, 1):
    sc = {"n": i, "title": s["title"], "pov": s["pov"], "narration": plain(s["v"]), "narration_voiced": s["v"],
          "image_prompt": s["img"], "shots": s["shots"], "sound": s["sound"], "refs": s["refs"], "voice_mood": s["mood"]}
    for k in ("beat", "must", "must_not", "own_rules"):
        if s.get(k):
            sc[k] = s[k]
    ep["scenes"].append(sc)
ep004 = S.load_episode("ep004")
ep["voice_engine"] = ep004["voice_engine"]
ep["max_credits"] = 330
ep["music_credit"] = ("Music by Kevin MacLeod (incompetech.com), licensed under Creative Commons: By Attribution 4.0 — "
                      + ", ".join(f"\"{m['title']}\"" for m in ep["music"]))
S.save_episode(ep)
w = [len(s["narration"].split()) for s in ep["scenes"]]
print(len(w), "sahne", sum(w), "kelime", min(w), max(w), "≈", round(sum(w)/2.81/1.06/60 + len(w)*0.6/60, 1), "dk")
print(S.estimate(ep))
